version: '3.8'
services:
  postgres:
    image: postgres:16
    container_name: petapi-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: petdb
    ports:
      - "5433:5432"
    volumes:
      - petapi-data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: petapi-backend
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/petdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      - postgres

  frontend:
    build: ./frontend
    container_name: petapi-frontend
    restart: always
    ports:
      - "5173:80"
    depends_on:
      - backend

  pgadmin:
    image: dpage/pgadmin4
    container_name: petapi-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"

volumes:
  petapi-data:
